ZOE_BASE="$ZOE_HOME/src"
ZOE_PIDS="$ZOE_HOME/logs/pids"
ZOE_LOGS="$ZOE_HOME/logs"
ENABLED_AGENTS="log users lists banking inventory courses broadcast twitter jabber mail activities"
MAILMAN="root@ibor.gul.es"
