ZOE_BASE="../src"
ZOE_PIDS="../logs/pids"
ZOE_LOGS="../logs"
PYTHON3="python3.3"
PYTHON2="python2.7"
ENABLED_AGENTS="log users lists banking inventory courses broadcast twitter jabber mail activities"
SERVER_HOST=localhost
SERVER_PORT=30000
MAILMAN="root@ibor.gul.es"
